apiVersion: v2
name: onecx-search-config-bff
version: 0.0.0
appVersion: 0.0.0
description: OneCX Search Config BFF
keywords:
  - search-config
sources:
  - https://github.com/onecx/onecx-search-config-bff
maintainers:
  - name: Tkit Developer
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-quarkus-app
    alias: app
    version: ^0
    repository: oci://ghcr.io/onecx/charts
